CustomUser/urls.py
from . import views

from django.urls import path



app_name = 'CustomUser'

urlpatterns = [
    path('create/', views.UserCreate.as_view(), name='create'),
    path('login/', views.UserLogin.as_view(), name= 'login'),
    path('profile/<uuid:uuid_value>/', views.UserProfile.as_view(), name = 'profile'),
    path('update/<uuid:uuid_value>/', views.UserUpdate.as_view(), name = 'update'),
    path('change_email/', views.UserOTPVerifyEmailChange.as_view(), name = 'change_email'),
    path('password_change/', views.UserPasswordChange.as_view(), name = 'password_change'),
    path('password_reset/', views.UserPasswordReset.as_view(), name = 'password_reset'),
    path('password_reset_done/', views.UserPasswordResetDone.as_view(), name = 'password_reset_done'),
    path('password_reset_confirm/<uidb64>/<token>/', views.UserPasswordResetConfirm.as_view(), name = 'password_reset_confirm'),
    path('logout/', views.UserLogout.as_view(), name = 'logout'),
    path('delete/', views.UserDelete.as_view(), name = 'delete'),
    path('otp_verify/', views.UserOTPVerify.as_view(), name= 'otp_verify'),
    ]

CustomUser/models.py
import uuid
import re

from django.db import models
from django.urls import reverse
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.validators import UnicodeUsernameValidator
from django.contrib.auth.models import AbstractUser


# Create your MODELS here.



def validate_gmail(value):
    # GMAIL validation logic; 
    if re.split('@', value)[-1] != 'gmail.com':
        raise ValidationError(
            _('%(value)s is NOT a valid GMAIL account. Only Gmail address is allowed'),
            params={'value': value},
        )



class user(AbstractUser):

    """
    A fully featured Custom User Model with admin-compliant permissions. 
    Email and password are required. Other fields are optional.
    """

    username_validator = UnicodeUsernameValidator()

    uuid_value = models.UUIDField(
        primary_key=False,
        default=uuid.uuid4,
        editable=False,
        null=False)
    email = models.EmailField(
        _('email address'), 
        unique=True, 
        blank=False, 
        null=False, )
    temp_email = models.EmailField(
        _('Temporary email address'), 
        blank=True, 
        null=True, )
    username = models.CharField(
        _('username'), 
        max_length=150, 
        unique=True, 
        blank=True, 
        null=True, 
        help_text=_('Optional. 150 characters or fewer. Letters, digits and @/./+/-/_ only.'), 
        validators=[username_validator], 
        error_messages={'unique': _("A user with that username already exists.")})
    is_active = models.BooleanField(
        _('active'),
        default=True,
        help_text=_(
            'Designates whether this user should be treated as active. '
            'Unselect this instead of deleting accounts.'
        ))

    # Other Fields can be included according to project's needs

    def get_absolute_url(self):
        return reverse('CustomUser:profile', kwargs={'uuid_value': self.uuid_value})

    EMAIL_FIELD = 'email'
    USERNAME_FIELD = EMAIL_FIELD
    REQUIRED_FIELDS = ['username']

    class Meta:
        abstract = False

CustomUser/forms.py
from .models import user as c_user

from django.db import transaction
from django.utils.translation import gettext_lazy as _
from django.contrib.auth import authenticate
from django.contrib.auth.forms import UserCreationForm, UsernameField
from django import forms
from django.utils.translation import ngettext_lazy
from django.contrib.auth.forms import AuthenticationForm
from django.core.exceptions import ValidationError
from django.conf import settings

from django_otp.forms import OTPTokenForm



class CustomUserCreationForm(UserCreationForm):
    # A Custom User-Creation-form is needed since we're using a customized user model

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.is_active = False # Setting it to False; because the email hasn't been verified yet
            user.save()
        return user
    
    class Meta:
        model = c_user
        fields = ('first_name', 'last_name', 'email')
        field_classes = {'email': UsernameField}



class ModifiedAuthenticationForm(AuthenticationForm):
    # For unknown reasons (maybe in my case only), Django's built-in AuthenticationForm 
    # doesn't show any "inactive" error when the user trying to Login is inactive. So, 
    # I had to modify the "clean()" method accordingly.

    error_messages = {
        'invalid_login': _(
            "Please enter a correct %(username)s and password. Note that both fields may be case-sensitive."
        ),
        'inactive': _(
            "Your account is inactive. Please activate it first. If you have just created this account, click on the link sent to your email address"
        ),
    }


    def clean(self):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')

        if username is not None and password:
            self.user_cache = authenticate(self.request, username=username, password=password)

            if self.user_cache is None:
                try:
                    unauthenticated_user = c_user.objects.get(email=username) 
                    # because "authenticate()" method returns None if the user is inactive or not authenticated.                   
                except:
                    unauthenticated_user = None
                finally:
                    if unauthenticated_user and not unauthenticated_user.is_active:
                        # Instead of calling the "confirm_login_allowed(unauthenticated_user)"; I'm 
                        # directly raising a ValidationError. You can call the method if it's needed for your project.
                        raise ValidationError(self.error_messages['inactive'], code='inactive',)
                    else:
                        raise self.get_invalid_login_error()
                        
        return self.cleaned_data



class CustomUserDeletionForm(forms.Form):
    # This form is used while deleting a user

    password = forms.CharField(
        label=_("Password"),
        strip=False,
        widget=forms.PasswordInput(attrs={'autocomplete': 'Your-password'})
        )



class CustomOTPTokenForm(OTPTokenForm):
    # The built-in "OTPTokenForm" requires the current user object to be passed to it 
    # as an argument, which can be done in the views.py. Instead, I inherited the form 
    # class itself and customized it for ease. This CustomOTPTokenForm is fully 
    # compatible with any LoginView.

    otp_error_messages = {
        'token_required': _('Please enter your OTP token.'),
        'challenge_exception': _('Error generating OTP Token: {0}'),
        'not_interactive': _('The selected OTP device is not interactive'),
        'challenge_message': _('OTP Token: {0}'),
        'invalid_token': _('Invalid token. Please make sure you have entered it correctly.'),
        'n_failed_attempts': ngettext_lazy(
            "Verification temporarily disabled because of %(failure_count)d failed attempt, please try again soon.",
            "Verification temporarily disabled because of %(failure_count)d failed attempts, please try again soon.",
            "failure_count"),
        'verification_not_allowed': _("Verification of the token is currently disabled"),
    }

    def __init__(self, request=None, *args, **kwargs):
        super().__init__(request.user, *args, **kwargs)

        self.user = request.user
        self.fields['otp_device'].choices = self.device_choices(request.user)



class CustomOTPTokenFormChangeEmail(CustomOTPTokenForm):
    """
    This form is built on top of the "django_otp.forms.OTPTokenForm" and modified to 
    serve the purpose of changing a "user.email" field upon a successful token-verification. 

    How it works: 
    First of, when called with 'Send OTP (Get Challenge)', the "EmailDevice.email" field 
    is filled with "form.cleaned_data['new_email']", and thus an OTP Token is delivered to 
    this email address. If the token-delivery is successful, the email address where the token 
    has been sent is saved to "user.temp_email" field (in DATABASE level). After that, when 
    a user submits a token; "clean_otp()" first checks if the current 
    "form.cleaned_data['new_email']" and "user.temp_email" match; if matched, then 
    the token is given to the "verify_token()" method for further verification; if they don't, then 
    "user.temp_email" is assigned the new value of the "form.cleaned_data['new_email']" and 
    "_handle_challenge()" is called to start the process again. Once the "verify_token()" method 
    successfully verifies a token, "user.email" is set to the value of "user.temp_email", 
    "user.temp_email" is set to None and the "user" object is saved in the database. "EmailDevice.name" 
    is also changed to the "user.email" and saved.
    """

    new_email = forms.EmailField()

    @staticmethod
    def device_choices(user):
        # We want to specify the email devices only.
        return list((d.persistent_id, d.name) for d in user.emaildevice_set.all())

    def clean_otp(self, user):
        """
        Processes the ``otp_*`` fields.

        :param user: A user that has been authenticated by the first factor
            (such as a password).
        :type user: :class:`~django.contrib.auth.models.User`
        :raises: :exc:`~django.core.exceptions.ValidationError` if the user is
            not fully authenticated by an OTP token.
        """
        if user is None:
            return

        validation_error = None

        with transaction.atomic():
            try:
                device = self._chosen_device(user)
                token = self.cleaned_data.get('otp_token')

                user.otp_device = None

                try:
                    if self.cleaned_data.get('otp_challenge'):
                        self._handle_challenge(device)
                    elif token:                       
                        if self.cleaned_data['new_email'] == user.temp_email: # check if the email address given previously (when clicking 'send token') and the current one (when clicking 'verify') match
                            user.otp_device = self._verify_token(user, token, device)
                        else:
                            # if they don't match, start the process again with the newly given email address
                            self._handle_challenge(device)
                    else:
                        raise forms.ValidationError(self.otp_error_messages['token_required'], code='token_required')
                finally:
                    if user.otp_device is None:
                        self._update_form(user)
                    if user.otp_device:
                        # OTP verification is successful
                        # Some cleaning up at the end; and most importantly, the assignment of the newly verified email address to "user.email"
                        user.email = user.temp_email
                        user.temp_email = None
                        user.save()
                        device.name = user.email
                        device.save()
                        

                    
            except forms.ValidationError as e:
                # Validation errors shouldn't abort the transaction, so we have
                # to carefully transport them out.
                validation_error = e

        if validation_error:
            raise validation_error


    def _handle_challenge(self, device):
        if c_user.objects.filter(email = self.cleaned_data['new_email']).exists():
            raise forms.ValidationError(
                self.otp_error_messages['challenge_exception'].format("This email address already exists to an account"), code='challenge_exception'
            )
        try:
            device.email = self.cleaned_data['new_email'] # The value of device.email is used to deliver the token
            challenge = device.generate_challenge() if (device is not None) else None
            if challenge:
                # if the token is successfully delivered to the new email address, then save it to user.temp_email field
                self.user.temp_email = device.email
                device.email = None
                device.save()
                self.user.save()
        except Exception as e:
            raise forms.ValidationError(
                self.otp_error_messages['challenge_exception'].format(e), code='challenge_exception'
            )
        else:
            if challenge is None:
                raise forms.ValidationError(self.otp_error_messages['not_interactive'], code='not_interactive')
            else:
                raise forms.ValidationError(
                    self.otp_error_messages['challenge_message'].format(challenge), code='challenge_message'
                )

CustomUser/templates/CustomUser/dj_e_v_mail_body.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Email Confirmation</title>
    </head>
    <body>
        <h1>You are almost there, {{ user.first_name }}!</h1><br>
        <h2>Please click <a href="{{ link }}">here</a> to confirm your account</h2>
        <h2>The token expires on {{ expiry|time:"TIME_FORMAT" }}</h2>
    </body>
</html>

CustomUser/templates/CustomUser/logged_out.html
{% block content %}

{% if messages %}
    <ul class="messages">
    {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message.tags }}: {{ message }}</li>
    {% endfor %}
    </ul>
{% endif %}

<p> You've been logged out. Thanks for spending some quality time with the web site today.</p>

<p><a href="{% url 'CustomUser:login' %}">Log In again</a></p>

{% endblock %}

CustomUser/templates/CustomUser/login.html
{% block content %}

{% if messages %}
    <ul class="messages">
    {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message.tags }}: {{ message }}</li>
    {% endfor %}
    </ul>
{% endif %}

{% if next %}
    {% if user.is_authenticated %}
        <p>Your account doesn't have access to this page. To proceed, please login with an account that has access.</p>
    {% else %}
        <p>Please login to see this page.</p>
    {% endif %}
{% endif %}

<form method="post">
{% csrf_token %}
{{ form.non_field_errors }}

    <table>
        <tr>
            <td>{{ form.username.label_tag }}</td>
            <td>{{ form.username }}</td>
        </tr>
        <tr>
            <td>{{ form.password.label_tag }}</td>
            <td>{{ form.password }}</td>
        </tr>
    </table>

    <input type="submit" value="login">
    <input type="hidden" name="next" value="{{ next }}">

</form>

<p><a href="{% url 'CustomUser:password_reset' %}">Forgotten password?</a></p>

<p><a href="{% url 'CustomUser:create' %}">Don't have an account?</a></p>

{% endblock %}

CustomUser/templates/CustomUser/password_change_form.html
{% block content %}

{% if messages %}
    <ul class="messages">
    {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message.tags }}: {{ message }}</li>
    {% endfor %}
    </ul>
{% endif %}

<div id="content-main">

    <form method="post">
    {% csrf_token %}
    {{ form.non_field_errors }}

        <div>

            <!-- {% if form.errors %}
                <p class="errornote">
                {% if form.errors.items|length == 1 %}
                    Please correct the error below.
                {% else %}
                    Please correct the errors below.
                {% endif %}
                </p>
            {% endif %} -->

            <p> Please enter your old password, for security's sake; and then enter your new password twice so we can verify you typed it in correctly. </p>

            <fieldset class="module aligned wide">

                <div class="form-row">
                    {{ form.old_password.errors }}
                    {{ form.old_password.label_tag }} {{ form.old_password }}
                </div>

                <div class="form-row">
                    {{ form.new_password1.errors }}
                    {{ form.new_password1.label_tag }} {{ form.new_password1 }}
                    {% if form.new_password1.help_text %}
                        <div class="help">{{ form.new_password1.help_text|safe }}</div>
                    {% endif %}
                </div>

                <div class="form-row">
                    {{ form.new_password2.errors }}
                    {{ form.new_password2.label_tag }} {{ form.new_password2 }}
                    {% if form.new_password2.help_text %}
                        <div class="help">{{ form.new_password2.help_text|safe }}</div>
                    {% endif %}
                </div>

            </fieldset>

            <div class="submit-row">
                <input type="submit" value="Change my password" class="default">
            </div>

            <p><a href="{% url 'CustomUser:password_reset' %}">Forgotten password?</a></p>

        </div>

    </form>

</div>

{% endblock %}

CustomUser/templates/CustomUser/password_reset_confirm.html
{% block content %}

{% if messages %}
    <ul class="messages">
    {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message.tags }}: {{ message }}</li>
    {% endfor %}
    </ul>
{% endif %}

{% if validlink %}

    <p> Please enter your new password twice so we can verify you typed it in correctly. </p>

    <form method="post">
    {% csrf_token %}
        <fieldset class="module aligned">
            <p> <b> {{form.user.get_username}} </b> </p>
            <div class="form-row field-password1">
                {{ form.new_password1.errors }}
                <label for="id_new_password1"> New password: </label>
                {{ form.new_password1 }}
            </div>
            <div class="form-row field-password2">
                {{ form.new_password2.errors }}
                <label for="id_new_password2"> Confirm password: </label>
                {{ form.new_password2 }}
            </div>
            <input type="submit" value="Change my password">
        </fieldset>
    </form>

{% else %}

    <p> The password reset link was invalid, possibly because it has already been used. Please request a new password reset. </p>

{% endif %}

{% endblock %}

CustomUser/templates/CustomUser/password_reset_done.html
{% block content %}

{% if messages %}
    <ul class="messages">
    {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message.tags }}: {{ message }}</li>
    {% endfor %}
    </ul>
{% endif %}

<p> We've emailed you instructions for setting your password. if an account exists with the email you entered, You should receive them shortly. </p>

<p> If you don't receive an email, please make sure you've entered the address you registered with, and check your spam folder. </p>

{% endblock %}

CustomUser/templates/CustomUser/password_reset_email.html
{% load i18n %}
{% autoescape off %}

{% blocktranslate %}
You're receiving this email because you requested a password reset for your user account at {{ site_name }}.
{% endblocktranslate %}

{% translate "Please go to the following page and choose a new password:" %}

{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'CustomUser:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}

{% translate 'Your username, in case you have forgotten:' %} {{ user.get_username }}

{% translate "Thanks for using our site!" %}

{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}

{% endautoescape %}

CustomUser/templates/CustomUser/password_reset_form.html
{% block content %}

{% if messages %}
    <ul class="messages">
    {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message.tags }}: {{ message }}</li>
    {% endfor %}
    </ul>
{% endif %}

<p> Forgotten your password? Enter your email address below, and we'll email instructions for setting a new one. </p>

<form method="post">{% csrf_token %}
    <fieldset class="module aligned">
        <div class="form-row field-email">
            {{ form.email.errors }}
            <label for="id_email">Email address:</label>
            {{ form.email }}
        </div>
        <input type="submit" value="Reset my password">
    </fieldset>
</form>

{% endblock %}

CustomUser/templates/CustomUser/user_change_email_form.html
{% if messages %}
    <ul class="messages">
    {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message.tags }}: {{ message }}</li>
    {% endfor %}
    </ul>
{% endif %}

<form method="POST">
{% csrf_token %}
{{ form.non_field_errors }}
    {% if form.get_user %}
        <div hidden class="form-row"> 
            {{ form.otp_device.errors }} Current Email Address: {{ form.otp_device }} 
        </div>
        <div class="form-row">
            <p>
                <label for="id_new_email">New email:</label>
                <input type="email" name="new_email" required id="id_new_email" value = "{{ request.user.temp_email }}">
                <input type="submit" name="otp_challenge" value="Send Token" />
            </p>
        </div>
    {% endif %}


    <div class="form-row"> {{ form.otp_token.errors }}{{ form.otp_token.label_tag }}{{ form.otp_token }} </div>
    
    <div class="submit-row">
        <p>
            <input type="submit" value="Verify"/>
        </p>
    </div>
</form>

CustomUser/templates/CustomUser/user_create_form.html
{% block content %}

{% if messages %}
    <ul class="messages">
    {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message.tags }}: {{ message }}</li>
    {% endfor %}
    </ul>
{% endif %}

<div class="content-section">

    <form method="POST">
    {% csrf_token %}
    {{ form.non_field_errors }}

        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Join Today!</legend>
            {{ form.as_p }}
        </fieldset>

        <div class="form-group">
            <button class="btn btn-outline-info" type="submit">Sign Up</button>
        </div>

    </form>

    <div class="border-top pt-3">
        <small class="text-muted">
            Already Have An Account? <a class="ml-2" href="{% url 'CustomUser:login' %}">Log In</a>
        </small>
    </div>

</div>

{% endblock content %}

CustomUser/templates/CustomUser/user_delete_form.html
{% block content %}

{% if messages %}
    <ul class="messages">
    {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message.tags }}: {{ message }}</li>
    {% endfor %}
    </ul>
{% endif %}

<form method="post">
{% csrf_token %}
{{ form.non_field_errors }}

    <p> {{user.first_name}}, Are you sure you want to delete your account <b>permanently</b>? </p>

    <p> <b>Note:</b> If you choose to delete your account, it's going to be deleted permanently from our database. Please proceed with precaution. </p>

    <p> For security reasons, please type your password correctly </p>

    {{ form.as_p }}

    <input type="submit" value="Delete My Account and Logout">

 </form>

 {% endblock %}

CustomUser/templates/CustomUser/user_otp_verify_form.html
{% if messages %}
    <ul class="messages">
    {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message.tags }}: {{ message }}</li>
    {% endfor %}
    </ul>
{% endif %}

<h2> OTP Verification Required </h2>

<form method="POST">
{% csrf_token %}
{{ form.non_field_errors }}

    {% if form.get_user %}
        <div class="form-row"> 
            {{ form.otp_device.errors }} 
            <p> Email Address to send an OTP Token: {{ form.otp_device }} <input type="submit" name="otp_challenge" value="Send Token" /> </p>
        </div>
    {% endif %}

    <div class="form-row"> 
        <p> {{ form.otp_token.errors }}{{ form.otp_token.label_tag }}{{ form.otp_token }} </p> 
    </div>

    <div class="submit-row">
        <p>
            <input type="submit" value="Verify"/>
        </p>
    </div>

</form>

CustomUser/templates/CustomUser/user_profile.html
{% if messages %}
    <ul class="messages">
    {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message.tags }}: {{ message }}</li>
    {% endfor %}
    </ul>
{% endif %}

Welcome to your Profile! <h1> {{ object.first_name }} </h1>

<p>First Name: {{ object.first_name }}</p>
<p>Last Name: {{ object.last_name }}</p>
<p>Email Address: {{ object.email }}</p>

<p> <a class="ml-2" href="{% url 'CustomUser:update' request.user.uuid_value %}"> Update Profile </a> </p>
<p> <a class="ml-2" href="{% url 'CustomUser:logout' %}"> Log out </a> </p>

CustomUser/templates/CustomUser/user_update_form.html
{% if messages %}
    <ul class="messages">
    {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message.tags }}: {{ message }}</li>
    {% endfor %}
    </ul>
{% endif %}

<form method="post">
{% csrf_token %}
{{form.non_field_errors}}

    {{ form.as_p }}
    <input type="submit" value="Update">
    <p> <a href="{% url 'CustomUser:change_email' %}"> Change Email </a> </p>
    <p> <a href="{% url 'CustomUser:password_change' %}"> Change Password </a> </p>
    <p> <a href="{% url 'CustomUser:delete' %}"> Delete Profile </a> </p>
    
</form>